/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        int testNum = 5;
        int[] testArray = Library.roll(testNum);

        boolean test = false;

        for(int i = 0; i < testNum; i++) {

            if (testArray[i] > 6 || testArray[i] < 1) {
                test = false;
                break;
            } else {
                test = true;
            }
        }
        assertTrue("someLibraryMethod should return 'true'", test);
    }
}
