/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static int[] roll(int n) {
        int[] result = new int[n];
        for (int i = 0; i < n;) {
            int num = (int)(Math.random() * (6 - 1) + 1);
            result[i] = num;
        }
        return result;
    }
}
